package gr.aegean.palaemon.rulesengine.rules;

import gr.aegean.palaemon.rulesengine.model.MessageBodyRequest;
import gr.aegean.palaemon.rulesengine.model.MessageBodyResponse;

global MessageBodyResponse messageBodyRes;






rule "MessageBody_r1_Stay_not_gr"
	when
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("WAIT"))

	then
		messageBodyRes.setContent("Please remain in your location. A crew member is on the way to escort you to the Master Station and will arrive to you really shortly.");
end

rule "Assume_EMERGENCY_Positions"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("4.1"))
	then
		messageBodyRes.setContent("Assume your emergency post now!!");
end


rule "MessageBody_r1_Follow_en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("MUSTERSTATION_1"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("Please follow the predefined path to Muster Station 1");
end

rule "MessageBody_r2_Follow_en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("Deck 7, MusterStation 1"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_4"))
		MessageBodyRequest(assignmentType == null)

	then
		messageBodyRes.setContent("Please follow the predefined path to Muster Station 1");
end


rule "MessageBody_r3_path3_Follow_en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("Deck 7, Muster Station"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_3"))
		MessageBodyRequest(assignmentType == null)

	then
		messageBodyRes.setContent("Please follow PATH_3 to Muster Station");
end

rule "MessageBody_r3_path4_Follow_en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_4"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("Please remain in your location you are already at the Muster Station");
end




rule "MessageBody_r3_path2_Follow_en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("Deck 7, Muster Station"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_2"))
        MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("Please follow PATH_2 path to Muster Station");
end





rule "MessageBody_r1_Follow_gr"
	when
	    MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("MUSTERSTATION_1"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("Ακολουθήστε τον προκαθορισμένο δρόμο διαφυφής για το Σταθμό Συγκέτρωσης 1");
end





// ***************** REAL RULES ************************

rule "Alert_Passengers_en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("5.1"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(assignmentType == null)
	then
		//messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Emergency Alert</h2><div style='font-size: x-large;'><b >Fire Onboard. Prepare for immediate evacuation. <span style='color: red'>This is not a drill!</span></b><div>You will receive instructions on your phone in a few seconds.</div> </div></main>:: sound: siren");
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'></h2><div style='font-size: x-large;'><b ><span style='color: red'></span></b><div></div> </div></main>:: sound: siren");
		messageBodyRes.setVisualAid("alert.png");
		System.out.println("Rule Alert_Passengers_en used");
end




rule "Alert_Passengers_gr"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("5.1"))
		MessageBodyRequest(language != null && language.equals("gr"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3> Ειδοποίηση έκτακτης ανάγκης: εξαιρετικά επείγουσα</h3><div><b>Πυρκαγιά στο πλοίο. Προετοιμαστείτε για άμεση εκκένωση.<span style='color: red'>Δεν πρόκειται για δοκιμαστική άσκηση!!</span></b></div>");
		messageBodyRes.setVisualAid("alert.png");
		System.out.println("Rule Alert_Passengers_gr used");
end






// ************ Start of MUSTERING MESSAGE RULES RULES ********************************************************





rule "Inform_Passengers_gr"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.2"))
		MessageBodyRequest(language != null && language.equals("gr"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Emergency Instructions</h2>" +
                                                  "<div style='font-size: x-large;'>  Σε περίπτωση που χαθείτε ακολουθήστε την ταμπέλα για τον <b>Σταθμό Συγκέντρωσης Β </b>. Θα βρείτε σωσίβια εκεί.</div>"+
                                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("muster-point.png");
		System.out.println("Rule Inform_Passengers_gr used");
end

rule "Inform_Passengers_en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.2"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Emergency Instructions</h2>" +
                                          "<div style='font-size: x-large;'> You are assigned to <b>Muster Station B</b>. Life Jackets will be provided to you there</div>"+
                                          "</main>:: sound: siren");
        messageBodyRes.setVisualAid("muster-point.png");
		System.out.println("Rule Inform_Passengers_en used");
end






// ************ EMBARKATION RULES ********************************************************
rule "Embarkation_en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("7.1"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(assignmentType == null)
	then
        messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Embarkation Instructions</h2>" +
                                          "<div style='font-size: x-large;'> Your Embarkation Group is <b>Group 1</b>. Follow the crew's instructions to find your assembly area.</div>"+
                                          "</main>:: sound: siren");
		System.out.println("Rule Embarkation_en used");
end

rule "Embarkation_gr"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("7.1"))
		MessageBodyRequest(language != null && language.equals("gr"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Embarkation Instructions</h2>" +
                                                  "<div style='font-size: x-large;'>Ανήκετε στην ομάδα επιβίβασης <b>ΟΜΑΔΑ 1</b>. Ακολουθήστε τις οδηγίες του πληρώματος για να βρείτε το σημείο συγκέντρωσης της ομάδας σας.</div>"+
                                                  "</main>:: sound: siren");
		System.out.println("Rule Embarkation_gr used");
end

rule "Embarkation_part_2en"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("7.2"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Embarkation Instructions</h2>" +
                                                          "<div style='font-size: x-large;'>Group 1 passengers <b>move now to the Embarkation station B</b>. Keep your lifejacket on at all times.</div>"+
                                                          "</main>:: sound: siren");
		System.out.println("Rule Embarkation_en used");
end

rule "Embarkation_part_2_gr"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("7.2"))
		MessageBodyRequest(language != null && language.equals("gr"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Embarkation Instructions</h2>" +
                                                                  "<div style='font-size: x-large;'>Οι επιβάτες της ομάδας 1 <b>να μεταβούν τώρα στο Σταθμό Eπιβίβασης Β</b>.Διατηρήστε το σωσίβιό σας καθ' όλη τη διάρκεια.</div>"+
                                                                  "</main>:: sound: siren");
		System.out.println("Rule Embarkation_gr used");
end


// ******************* MUSTERING RULES ************************************************

rule "elyros_9_9BG1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P1"))
		MessageBodyRequest(geofence != null && geofence.equals("9BG1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                 // "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div style='font-size: x-large;'><b >Exit the VIP Lounge Area and find the staircase on your left. Use this stair two levels down to reach Deck 7. Use the door in front of you to enter the Master station area.</b></div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_9_9BG1 used");
end

rule "elyros_9_S9-8.1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P1"))
		MessageBodyRequest(geofence != null && geofence.equals("S9-8.1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Use this stair two levels down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_9_S9-8.1 used");
end
rule "elyros_9_S8-7.1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P1") || pathId != null && pathId.equals("PATH_P2") || pathId != null && pathId.equals("PATH_P3") || pathId != null && pathId.equals("PATH_P4") || pathId != null && pathId.equals("PATH_P5") || pathId != null && pathId.equals("PATH_P6"))
		MessageBodyRequest(geofence != null && geofence.equals("S8-7.1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                "<div>Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>"+
                "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_9_S8-7.1 used");
end
rule "elyros_9_S7-6.1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P1") || pathId != null && pathId.equals("PATH_P2") || pathId != null && pathId.equals("PATH_P3") || pathId != null && pathId.equals("PATH_P4") || pathId != null && pathId.equals("PATH_P5") || pathId != null && pathId.equals("PATH_P6"))
		MessageBodyRequest(geofence != null && geofence.equals("S7-6.1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Use the door in front of you to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_9_S7-6.1 used");
end
rule "elyros_9_7BG4"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P1") || pathId != null && pathId.equals("PATH_P2") || pathId != null && pathId.equals("PATH_P3") || pathId != null && pathId.equals("PATH_P4") || pathId != null && pathId.equals("PATH_P5") || pathId != null && pathId.equals("PATH_P6"))
		MessageBodyRequest(geofence != null && geofence.equals("7BG4"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 20 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_9_7BG4 used");
end
rule "elyros_9_7BG5"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P1"))
		MessageBodyRequest(geofence != null && geofence.equals("7BG5"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 10 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_9_7BG5 used");
end


// -------------->CABIN RULES <-------------

//PATH_2
rule "elyros_8_8G1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P2"))
		MessageBodyRequest(geofence != null && geofence.equals("8G1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your left. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end
rule "elyros_8_S8-7.1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P2"))
		MessageBodyRequest(geofence != null && geofence.equals("S8-7.1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end


//PATH_3

rule "elyros_8_8G2"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P3"))
		MessageBodyRequest(geofence != null && geofence.equals("8G2"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your right. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end

//PATH_4

rule "elyros_8_8G3"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P4"))
		MessageBodyRequest(geofence != null && geofence.equals("8G3"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your right. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end

//PATH_5

rule "elyros_8_8G4"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P5"))
		MessageBodyRequest(geofence != null && geofence.equals("8G4"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your right. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end

//PATH_6

rule "elyros_8_8G5"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P6"))
		MessageBodyRequest(geofence != null && geofence.equals("8G5"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your right. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area</div>");
		messageBodyRes.setVisualAid("image1.png");
end


//PATH_7

rule "elyros_8_8G6"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P7"))
		MessageBodyRequest(geofence != null && geofence.equals("8G6"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your right. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end

rule "elyros_8_S8-7.2"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P7") || pathId != null && pathId.equals("PATH_P8"))
		MessageBodyRequest(geofence != null && geofence.equals("S8-7.2"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end

rule "elyros_8_7BG1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P7") || pathId != null && pathId.equals("PATH_P8") || pathId != null && pathId.equals("PATH_P9") || pathId != null && pathId.equals("PATH_P10")|| pathId != null && pathId.equals("PATH_P11"))
		MessageBodyRequest(geofence != null && geofence.equals("7BG1"))
		MessageBodyRequest(assignmentType == null)
	then
	    messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
	    "<div>Move straight for 150 meters to enter the Master station area.</div>");
	    messageBodyRes.setVisualAid("image1.png");
end

rule "elyros_8_7BG2"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P7") || pathId != null && pathId.equals("PATH_P8"))
		MessageBodyRequest(geofence != null && geofence.equals("7BG2")|| pathId != null && pathId.equals("PATH_P9")|| pathId != null && pathId.equals("PATH_P10")|| pathId != null && pathId.equals("PATH_P11"))
	    MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Walk 120 meters in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end

rule "elyros_8_7BG3"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P7") || pathId != null && pathId.equals("PATH_P8")|| pathId != null && pathId.equals("PATH_P9")|| pathId != null && pathId.equals("PATH_P10")|| pathId != null && pathId.equals("PATH_P11"))
		MessageBodyRequest(geofence != null && geofence.equals("7BG3"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Walk 100 meters in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end

rule "elyros_8_7BG4"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P7") || pathId != null && pathId.equals("PATH_P8")|| pathId != null && pathId.equals("PATH_P9")|| pathId != null && pathId.equals("PATH_P10")|| pathId != null && pathId.equals("PATH_P11"))
		MessageBodyRequest(geofence != null && geofence.equals("7BG4"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Walk 70 meters in front of you to enter the Master station area</div>");
		messageBodyRes.setVisualAid("image1.png");
end

rule "elyros_8_7BG5"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P7") || pathId != null && pathId.equals("PATH_P8") || pathId != null && pathId.equals("PATH_P9")|| pathId != null && pathId.equals("PATH_P10")|| pathId != null && pathId.equals("PATH_P11"))
		MessageBodyRequest(geofence != null && geofence.equals("7BG5"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent( "<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Walk 50 meters in front of you to enter the Master station area</div>");
		messageBodyRes.setVisualAid("image1.png");
end



//PATH_8

rule "elyros_8_8G7"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P8"))
		MessageBodyRequest(geofence != null && geofence.equals("8G7"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your left. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area</div>");
		messageBodyRes.setVisualAid("image1.png");
end




// PATH_9
rule "elyros_8_8G8"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P9"))
		MessageBodyRequest(geofence != null && geofence.equals("8G8"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your right. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area</div>");
		messageBodyRes.setVisualAid("image1.png");
end

rule "elyros_8_S8-7.3"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("S8-7.3"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P9") || pathId != null && pathId.equals("PATH_P10") || pathId != null && pathId.equals("PATH_P11") )
		MessageBodyRequest(geofence != null && geofence.equals("S8-7.3"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area</div>");
		messageBodyRes.setVisualAid("image1.png");
end

//PATH_10

rule "elyros_8_8G9"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P10"))
		MessageBodyRequest(geofence != null && geofence.equals("8G9"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your left. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area.</div>");
		messageBodyRes.setVisualAid("image1.png");
end

//PATH_11

rule "elyros_8_8G10"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P11"))
		MessageBodyRequest(geofence != null && geofence.equals("8G10"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<h3>Mustering Instructions</h3><div>Go now to the Muster Station 'B'. Access is via the following path:</div>" +
		"<div>Exit your Cabin and find the staircase on your left. Use this stair one level down to reach Deck 7. Use the door in front of you to enter the Master station area</div>");
		messageBodyRes.setVisualAid("image1.png");
end


// end of -------->CABIN RULES<----------------


rule "elyros_7_7DG1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7DG4"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P12"))
		MessageBodyRequest(geofence != null && geofence.equals("7DG1"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'D'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 150 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule aelyros_7_7DG1 used");
end

rule "elyros_7_7DG2"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7DG4"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P13"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'D'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 100 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7DG2 used");
end

rule "elyros_7_7DG3"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7DG4"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P14"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'D'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 50 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7DG3 used");
end

rule "elyros_7_7DG4"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7DG4"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P15"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'D'. Access is via the following path:</b></div>"+
                                  "<div>You are in the Master Station area. Follow the crew and the rest of the passengers</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7DG4 used");
end

rule "elyros_7_7DG3_alt"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P16"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'D'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 200 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7DG3_alt used");
end

rule "elyros_7_7CG1_alt"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P17"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 150 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7DG1_alt used");
end

rule "elyros_7_7CG2_alt"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P18"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                 "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                 "<div>Move straight for 100 meters to enter the Master station area.</div>"+
                                 "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7DG2_alt used");
end

rule "elyros_7_7BG1"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P19"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 70 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7BG1 used");
end

rule "elyros_7_7BG2"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P20"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 50 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7BG2 used");
end

rule "elyros_7_7BG3"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P21"))
		MessageBodyRequest(assignmentType == null)
	then
	messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                               "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                               "<div>Move straight for 40 meters to enter the Master station area.</div>"+
                               "</main>:: sound: siren");
	messageBodyRes.setVisualAid("image1.png");
	System.out.println("Rule elyros_7_7BG3 used");
end

rule "elyros_7_7BG5"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P22"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 20 meters to enter the Master station area.</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7BG5 used");
end

rule "elyros_7_7BG6"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(geofence != null && geofence.equals("7BG6"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent(
		"<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
        "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
        "<div>You are in the Master Station area. Follow the crew and the rest of the passengers</div>"+
        "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7BG6 used");
end


rule "elyros_7_7DG1, 7DG2, 7DG3, 7CG1, 7CG2, 7BG1, 7BG2, 7BG6"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P24"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'B'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 200 meters to enter the Master station area</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7DG1, 7DG2, 7DG3, 7CG1, 7CG2, 7BG1, 7BG2, 7BG6 used");
end

rule "elyros_7_7DG2, 7DG3, 7CG1, 7CG2, 7BG1, 7BG2, 7BG6"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("7BG6"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P25"))
		MessageBodyRequest(assignmentType == null)
	then
		messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                  "<div style='font-size: x-large;'><b >Go now to the Muster Station 'BSS'. Access is via the following path:</b></div>"+
                                  "<div>Move straight for 150 meters to enter the Master station area</div>"+
                                  "</main>:: sound: siren");
		messageBodyRes.setVisualAid("image1.png");
		System.out.println("Rule elyros_7_7DG2, 7DG3, 7CG1, 7CG2, 7BG1, 7BG2, 7BG6 used");
end


// START  -------->D9 NEW  RULES<----------------
rule "PATH_26_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P26"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                         // "<div style='font-size: x-large;'><b >Go now to the Muster Station'. Access is via the following path:</b></div>"+
"<div style='font-size: x-large;'> <b>  <p>Exit Room and turn left </p><p>Cross the Door </p><p>Cross first door on the right </p><p>Move Straight </p><p>Cross Muster Station door </p></b></div>"+
                                          "</main>:: sound: siren");

		messageBodyRes.setVisualAid("image_p26.png");
		System.out.println("Rule PATH_26_Message used");
end

rule "PATH_27_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P27"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                          "<div style='font-size: x-large;'><b>   <p>Exit Room and turn right. </p><p>Cross fist left door </p><p>Cross Muster Station door </p></b></div>"+

                                          "</main>:: sound: siren");

		messageBodyRes.setVisualAid("image_p27.png");
		System.out.println("Rule PATH_27_Message used");
end

rule "PATH_28_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P28"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                          //"<div style='font-size: x-large;'><b >Go now to the Muster Station'. Access is via the following path:</b></div>"+
                                        "<div style='font-size: x-large;'> <b>  <p>Exit Cabin and turn left </p><p>Cross Muster Station Door </p></b></div>"+
                                          "</main>:: sound: siren");

		messageBodyRes.setVisualAid("image_p28.png");
		System.out.println("Rule PATH_28_Message used");
end

rule "PATH_29_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P29"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                          //"<div style='font-size: x-large;'><b >Go now to the Muster Station'. Access is via the following path:</b></div>"+
                                        "<div style='font-size: x-large;'> <b>  <p>Exit Cabin and turn left </p><p>Cross Muster Station Door </p></b></div>"+
                                          "</main>:: sound: siren");

		messageBodyRes.setVisualAid("image_p29.png");
		System.out.println("Rule PATH_29_Message used");
end

rule "PATH_30_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P30"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                          //"<div style='font-size: x-large;'><b >Go now to the Muster Station'. Access is via the following path:</b></div>"+
                                          "<div style='font-size: x-large;'> <b>  <p>Cross first left door </p><p>Cross Muster Station Door </p></b></div>"+
                                          "</main>:: sound: siren");

		messageBodyRes.setVisualAid("image_p30.png");
		System.out.println("Rule PATH_30_Message used");
end



rule "PATH_31_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P31"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                          //"<div style='font-size: x-large;'><b >Go now to the Muster Station'. Access is via the following path:</b></div>"+
                                          "<div style='font-size: x-large;'> <b>  <p>Exit room and move straight </p><p>Cross Muster Station Door </p></b></div>"+
                                          "</main>:: sound: siren");

		messageBodyRes.setVisualAid("image_p31.png");
		System.out.println("Rule PATH_31_Message used");
end


rule "PATH_32_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P32"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                          //"<div style='font-size: x-large;'><b >Go now to the Muster Station'. Access is via the following path:</b></div>"+
                                          "<div style='font-size: x-large;'> <b>  <p>Move Straight until the end of the corridor </p><p>Cross Muster Station Door </p></b></div>"+
                                          "</main>:: sound: siren");

		messageBodyRes.setVisualAid("image_p32.png");
		System.out.println("Rule PATH_32_Message used");
end

rule "PATH_33_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P33"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                          //"<div style='font-size: x-large;'><b >Go now to the Muster Station'. Access is via the following path:</b></div>"+
                                          "<div style='font-size: x-large;'> <b>  <p>You are at the Muster Station. Stay here! </p></b></div>"+
                                          "</main>:: sound: siren");

	    System.out.println("Rule PATH_33_Message used");
end


rule "PATH_34_Message"
	when
		MessageBodyRequest(messageCode != null && messageCode.equals("6.3"))
		MessageBodyRequest(language != null && !language.equals("gr"))
		MessageBodyRequest(action!= null && action.equals("FOLLOW"))
		MessageBodyRequest(musteringStation != null && musteringStation.equals("9CG0"))
		MessageBodyRequest(pathId != null && pathId.equals("PATH_P34"))
		MessageBodyRequest(assignmentType == null)
	then
		 messageBodyRes.setContent("<header></header><main><h2 style='color: red; text-align: center;'>Mustering Instructions</h2>" +
                                          //"<div style='font-size: x-large;'><b >Go now to the Muster Station'. Access is via the following path:</b></div>"+
                                          "<div style='font-size: x-large;'> <b>  <p>Exit room and turn right </p><p>Cross first left door </p> <p>Cross Muster Station door </p></b></div>"+
                                          "</main>:: sound: siren");

		messageBodyRes.setVisualAid("image_p34.png");
		System.out.println("Rule PATH_33_Message used");
end