package gr.aegean.palaemon.rulesengine.rules;

import gr.aegean.palaemon.rulesengine.model.PhaseTask;
import gr.aegean.palaemon.rulesengine.model.MessageObject;
import gr.aegean.palaemon.rulesengine.model.MessageBodyRequest;
import gr.aegean.palaemon.rulesengine.model.MessageBodyResponse;
//



global MessageObject messageObject;


rule "r1"
	when
		PhaseTask(phase.equals("4"))
		PhaseTask(task.equals("1"))
	then
		messageObject.setType("t1");
		System.out.println("Rule r1 used");
end

rule "r2"
	when
		PhaseTask(phase.equals("4"))
		PhaseTask(task.equals("4.1"))
	then
		messageObject.setMessageCode("4.1");
		messageObject.setAudience("crew");
		System.out.println("Rule r2 used");
end

rule "r3"
	when
		PhaseTask(phase.equals("5"))
		PhaseTask(task.equals("5.1"))
	then
		messageObject.setMessageCode("5.1");
		messageObject.setAudience("passengers");
		System.out.println("Rule r3 used");
end


rule "r3.1"
	when
		PhaseTask(phase.equals("5"))
		PhaseTask(task.equals("5.11"))
	then
		messageObject.setMessageCode("5.11");
		messageObject.setAudience("passengers");
		System.out.println("Rule r3.1 used");
end


rule "r3.2"
	when
		PhaseTask(phase.equals("5"))
		PhaseTask(task.equals("5.12"))
	then
		messageObject.setMessageCode("5.12");
		messageObject.setAudience("passengers");
		System.out.println("Rule r3.2 used");
end


rule "r7"
	when
		PhaseTask(task.equals("7.1"))
	then
		messageObject.setMessageCode("7.1");
		messageObject.setAudience("both");
		System.out.println("Rule r7 used");
end


rule "r7.2"
	when
		PhaseTask(task.equals("7.2"))
	then
		messageObject.setMessageCode("7.2");
		messageObject.setAudience("both");
		System.out.println("Rule r72 used");
end


rule "r6"
	when
		PhaseTask(task.equals("6.0"))
	then
		messageObject.setMessageCode("6.0");
		messageObject.setAudience("passengers");
		System.out.println("Rule r0 used");
end


rule "r4"
	when
		PhaseTask(task.equals("6.2"))
	then
		messageObject.setMessageCode("6.2");
		messageObject.setAudience("passengers");
		System.out.println("Rule r4 used");
end

rule "r5"
	when
		PhaseTask(task.equals("6.3"))
	then
		messageObject.setMessageCode("6.3");
		messageObject.setAudience("passengers");
		System.out.println("Rule r5 used");
end
